all:
	cd think;make clean;make;make install;cd ..
	cd think_dbf;make clean;make;make install;cd ..
	cd tools;make clean;make;make install;cd ..
	cd logserver;make clean;make;make install;cd ..
	cd examples;make clean;make;make install;cd ..
clean:
	cd think;make clean;cd ..
	cd think_dbf;make clean;cd ..
	cd tools;make clean;cd ..
	cd logserver;make clean;cd ..
	cd examples;make clean;cd ..
