del /F /S /Q Release
nmake /f dbfcreate.mak CFG="dbfcreate - Win32 Release"
nmake /f dbfinsert.mak CFG="dbfinsert - Win32 Release"
nmake /f dbfload.mak CFG="dbfload - Win32 Release"
nmake /f dbfshow.mak CFG="dbfshow - Win32 Release"
nmake /f dbfstat.mak CFG="dbfstat - Win32 Release"
nmake /f dbcreate.mak CFG="dbcreate - Win32 Release"
nmake /f dbinsert.mak CFG="dbinsert - Win32 Release"
nmake /f dbload.mak CFG="dbload - Win32 Release"
nmake /f dbshow.mak CFG="dbshow - Win32 Release"
nmake /f dbstat.mak CFG="dbstat - Win32 Release"
nmake /f getcfg.mak CFG="getcfg - Win32 Release"
nmake /f getconf.mak CFG="getconf - Win32 Release"
nmake /f logsend.mak CFG="logsend - Win32 Release"
nmake /f logview.mak CFG="logview - Win32 Release"
nmake /f showcfg.mak CFG="showcfg - Win32 Release"
nmake /f showconf.mak CFG="showconf - Win32 Release"
nmake /f showerr.mak CFG="showerr - Win32 Release"
nmake /f shmqcreate.mak CFG="shmqcreate - Win32 Release"
nmake /f shmqget.mak CFG="shmqget - Win32 Release"
nmake /f shmqput.mak CFG="shmqput - Win32 Release"
nmake /f shmqstat.mak CFG="shmqstat - Win32 Release"
nmake /f glpeek.mak CFG="glpeek - Win32 Release"
nmake /f netpeek.mak CFG="netpeek - Win32 Release"
nmake /f hello.mak CFG="hello - Win32 Release"

pause
